#!/usr/bin/env node

var stdin = process.openStdin();
var EventEmitter = require('events').EventEmitter;

var buffer = "";

var convert = require('./index');

stdin.setEncoding('utf8');
stdin.on('data', function (chunk) {
    buffer += chunk;
});

stdin.on('end', function () {
    process.stdout.write(convert(buffer));
});
